[2020-01-20 01:31:59 +0800] [20673] [DEBUG] Current configuration:
  config: gunicorn_config_dev.py
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 12
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus
  daemon: True
  raw_env: []
  pidfile: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/gunicorn.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/debug.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f5b84df6320>
  on_reload: <function OnReload.on_reload at 0x7f5b84df6440>
  when_ready: <function WhenReady.when_ready at 0x7f5b84df6560>
  pre_fork: <function Prefork.pre_fork at 0x7f5b84df6680>
  post_fork: <function Postfork.post_fork at 0x7f5b84df67a0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f5b84df68c0>
  worker_int: <function WorkerInt.worker_int at 0x7f5b84df69e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f5b84df6b00>
  pre_exec: <function PreExec.pre_exec at 0x7f5b84df6c20>
  pre_request: <function PreRequest.pre_request at 0x7f5b84df6d40>
  post_request: <function PostRequest.post_request at 0x7f5b84df6dd0>
  child_exit: <function ChildExit.child_exit at 0x7f5b84df6ef0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f5b84cc5050>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f5b84cc5170>
  on_exit: <function OnExit.on_exit at 0x7f5b84cc5290>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-01-20 01:31:59 +0800] [20673] [INFO] Starting gunicorn 20.0.4
[2020-01-20 01:31:59 +0800] [20673] [DEBUG] Arbiter booted
[2020-01-20 01:31:59 +0800] [20673] [INFO] Listening at: http://0.0.0.0:8080 (20673)
[2020-01-20 01:31:59 +0800] [20673] [INFO] Using worker: sync
[2020-01-20 01:31:59 +0800] [20684] [INFO] Booting worker with pid: 20684
[2020-01-20 01:31:59 +0800] [20685] [INFO] Booting worker with pid: 20685
[2020-01-20 01:31:59 +0800] [20686] [INFO] Booting worker with pid: 20686
[2020-01-20 01:31:59 +0800] [20687] [INFO] Booting worker with pid: 20687
[2020-01-20 01:32:00 +0800] [20688] [INFO] Booting worker with pid: 20688
[2020-01-20 01:32:00 +0800] [20689] [INFO] Booting worker with pid: 20689
[2020-01-20 01:32:00 +0800] [20691] [INFO] Booting worker with pid: 20691
[2020-01-20 01:32:00 +0800] [20692] [INFO] Booting worker with pid: 20692
[2020-01-20 01:32:00 +0800] [20693] [INFO] Booting worker with pid: 20693
[2020-01-20 01:32:00 +0800] [20694] [INFO] Booting worker with pid: 20694
[2020-01-20 01:32:00 +0800] [20695] [INFO] Booting worker with pid: 20695
[2020-01-20 01:32:00 +0800] [20696] [INFO] Booting worker with pid: 20696
[2020-01-20 01:32:00 +0800] [20673] [DEBUG] 12 workers
[2020-01-20 01:32:22 +0800] [20756] [DEBUG] Current configuration:
  config: gunicorn_config_dev.py
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 12
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus
  daemon: True
  raw_env: []
  pidfile: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/gunicorn.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/debug.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f11ce4b0320>
  on_reload: <function OnReload.on_reload at 0x7f11ce4b0440>
  when_ready: <function WhenReady.when_ready at 0x7f11ce4b0560>
  pre_fork: <function Prefork.pre_fork at 0x7f11ce4b0680>
  post_fork: <function Postfork.post_fork at 0x7f11ce4b07a0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f11ce4b08c0>
  worker_int: <function WorkerInt.worker_int at 0x7f11ce4b09e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f11ce4b0b00>
  pre_exec: <function PreExec.pre_exec at 0x7f11ce4b0c20>
  pre_request: <function PreRequest.pre_request at 0x7f11ce4b0d40>
  post_request: <function PostRequest.post_request at 0x7f11ce4b0dd0>
  child_exit: <function ChildExit.child_exit at 0x7f11ce4b0ef0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f11ce37f050>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f11ce37f170>
  on_exit: <function OnExit.on_exit at 0x7f11ce37f290>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-01-20 01:32:22 +0800] [20756] [INFO] Starting gunicorn 20.0.4
[2020-01-20 02:24:07 +0800] [22810] [DEBUG] Current configuration:
  config: gunicorn_config_dev.py
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 12
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus
  daemon: True
  raw_env: []
  pidfile: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/gunicorn.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/debug.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7f4eab4cd320>
  on_reload: <function OnReload.on_reload at 0x7f4eab4cd440>
  when_ready: <function WhenReady.when_ready at 0x7f4eab4cd560>
  pre_fork: <function Prefork.pre_fork at 0x7f4eab4cd680>
  post_fork: <function Postfork.post_fork at 0x7f4eab4cd7a0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7f4eab4cd8c0>
  worker_int: <function WorkerInt.worker_int at 0x7f4eab4cd9e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7f4eab4cdb00>
  pre_exec: <function PreExec.pre_exec at 0x7f4eab4cdc20>
  pre_request: <function PreRequest.pre_request at 0x7f4eab4cdd40>
  post_request: <function PostRequest.post_request at 0x7f4eab4cddd0>
  child_exit: <function ChildExit.child_exit at 0x7f4eab4cdef0>
  worker_exit: <function WorkerExit.worker_exit at 0x7f4eab39c050>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7f4eab39c170>
  on_exit: <function OnExit.on_exit at 0x7f4eab39c290>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-01-20 02:24:07 +0800] [22810] [INFO] Starting gunicorn 20.0.4
[2020-01-20 02:25:28 +0800] [22857] [DEBUG] Current configuration:
  config: gunicorn_config_dev.py
  bind: ['0.0.0.0:8080']
  backlog: 2048
  workers: 12
  worker_class: sync
  threads: 1
  worker_connections: 1000
  max_requests: 0
  max_requests_jitter: 0
  timeout: 30
  graceful_timeout: 30
  keepalive: 2
  limit_request_line: 4094
  limit_request_fields: 100
  limit_request_field_size: 8190
  reload: False
  reload_engine: auto
  reload_extra_files: []
  spew: False
  check_config: False
  preload_app: False
  sendfile: None
  reuse_port: False
  chdir: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus
  daemon: True
  raw_env: []
  pidfile: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/gunicorn.pid
  worker_tmp_dir: None
  user: 1000
  group: 1000
  umask: 0
  initgroups: False
  tmp_upload_dir: None
  secure_scheme_headers: {'X-FORWARDED-PROTOCOL': 'ssl', 'X-FORWARDED-PROTO': 'https', 'X-FORWARDED-SSL': 'on'}
  forwarded_allow_ips: ['127.0.0.1']
  accesslog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/access.log
  disable_redirect_access_to_syslog: False
  access_log_format: %(h)s %(l)s %(u)s %(t)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s"
  errorlog: /home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/app/log/debug.log
  loglevel: debug
  capture_output: False
  logger_class: gunicorn.glogging.Logger
  logconfig: None
  logconfig_dict: {}
  syslog_addr: udp://localhost:514
  syslog: False
  syslog_prefix: None
  syslog_facility: user
  enable_stdio_inheritance: False
  statsd_host: None
  dogstatsd_tags: 
  statsd_prefix: 
  proc_name: None
  default_proc_name: run:app
  pythonpath: None
  paste: None
  on_starting: <function OnStarting.on_starting at 0x7fc596e16320>
  on_reload: <function OnReload.on_reload at 0x7fc596e16440>
  when_ready: <function WhenReady.when_ready at 0x7fc596e16560>
  pre_fork: <function Prefork.pre_fork at 0x7fc596e16680>
  post_fork: <function Postfork.post_fork at 0x7fc596e167a0>
  post_worker_init: <function PostWorkerInit.post_worker_init at 0x7fc596e168c0>
  worker_int: <function WorkerInt.worker_int at 0x7fc596e169e0>
  worker_abort: <function WorkerAbort.worker_abort at 0x7fc596e16b00>
  pre_exec: <function PreExec.pre_exec at 0x7fc596e16c20>
  pre_request: <function PreRequest.pre_request at 0x7fc596e16d40>
  post_request: <function PostRequest.post_request at 0x7fc596e16dd0>
  child_exit: <function ChildExit.child_exit at 0x7fc596e16ef0>
  worker_exit: <function WorkerExit.worker_exit at 0x7fc596ce5050>
  nworkers_changed: <function NumWorkersChanged.nworkers_changed at 0x7fc596ce5170>
  on_exit: <function OnExit.on_exit at 0x7fc596ce5290>
  proxy_protocol: False
  proxy_allow_ips: ['127.0.0.1']
  keyfile: None
  certfile: None
  ssl_version: 2
  cert_reqs: 0
  ca_certs: None
  suppress_ragged_eofs: True
  do_handshake_on_connect: False
  ciphers: None
  raw_paste_global_conf: []
  strip_header_spaces: False
[2020-01-20 02:25:28 +0800] [22857] [INFO] Starting gunicorn 20.0.4
[2020-01-20 02:25:42 +0800] [20685] [DEBUG] GET /
[2020-01-20 02:25:57 +0800] [20691] [DEBUG] GET /
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20684)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20685)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20686)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20687)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20688)
[2020-01-20 20:38:04 +0800] [20684] [INFO] Worker exiting (pid: 20684)
[2020-01-20 20:38:04 +0800] [20685] [INFO] Worker exiting (pid: 20685)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20689)
[2020-01-20 20:38:04 +0800] [20686] [INFO] Worker exiting (pid: 20686)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20691)
[2020-01-20 20:38:04 +0800] [20687] [INFO] Worker exiting (pid: 20687)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20692)
[2020-01-20 20:38:04 +0800] [20688] [INFO] Worker exiting (pid: 20688)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20693)
[2020-01-20 20:38:04 +0800] [20689] [INFO] Worker exiting (pid: 20689)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20694)
[2020-01-20 20:38:04 +0800] [20691] [INFO] Worker exiting (pid: 20691)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20695)
[2020-01-20 20:38:04 +0800] [20692] [INFO] Worker exiting (pid: 20692)
[2020-01-20 20:38:04 +0800] [20695] [INFO] Worker exiting (pid: 20695)
[2020-01-20 20:38:04 +0800] [20694] [INFO] Worker exiting (pid: 20694)
[2020-01-20 20:38:04 +0800] [20693] [INFO] Worker exiting (pid: 20693)
[2020-01-20 20:38:04 +0800] [20673] [CRITICAL] WORKER TIMEOUT (pid:20696)
[2020-01-20 20:38:04 +0800] [20696] [INFO] Worker exiting (pid: 20696)
[2020-01-20 20:38:04 +0800] [24166] [INFO] Booting worker with pid: 24166
[2020-01-20 20:38:04 +0800] [24183] [INFO] Booting worker with pid: 24183
[2020-01-20 20:38:04 +0800] [20673] [DEBUG] 2 workers
[2020-01-20 20:38:04 +0800] [24200] [INFO] Booting worker with pid: 24200
[2020-01-20 20:38:04 +0800] [24214] [INFO] Booting worker with pid: 24214
[2020-01-20 20:38:05 +0800] [24215] [INFO] Booting worker with pid: 24215
[2020-01-20 20:38:05 +0800] [24166] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24166] [INFO] Worker exiting (pid: 24166)
[2020-01-20 20:38:05 +0800] [24183] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24200] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24183] [INFO] Worker exiting (pid: 24183)
[2020-01-20 20:38:05 +0800] [24200] [INFO] Worker exiting (pid: 24200)
[2020-01-20 20:38:05 +0800] [24216] [INFO] Booting worker with pid: 24216
[2020-01-20 20:38:05 +0800] [24214] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24214] [INFO] Worker exiting (pid: 24214)
[2020-01-20 20:38:05 +0800] [24215] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24215] [INFO] Worker exiting (pid: 24215)
[2020-01-20 20:38:05 +0800] [24216] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 583, in connect
    **kwargs)
  File "/usr/lib64/python3.7/socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib64/python3.7/socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/qiongwei/mycode/pythonenv/virtualenv/pingpongus/run.py", line 10, in <module>
    db = pymysql.connect("http://db.pingpongus.com", "root", "root", "mysql")
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/__init__.py", line 94, in Connect
    return Connection(*args, **kwargs)
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 325, in __init__
    self.connect()
  File "/home/qiongwei/mycode/pythonenv/virtualenv/lib/python3.7/site-packages/pymysql/connections.py", line 630, in connect
    raise exc
pymysql.err.OperationalError: (2003, "Can't connect to MySQL server on 'http://db.pingpongus.com' ([Errno -2] Name or service not known)")
[2020-01-20 20:38:05 +0800] [24216] [INFO] Worker exiting (pid: 24216)
